In [31]:
import numpy as np

In [46]:
def statistics(pred_labels, true_labels):
    # Create a confusion matrix
    num_classes = 3
    confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)

    # Populate the confusion matrix
    for true, pred in zip(true_labels, pred_labels):
        confusion_matrix[true, pred] += 1

    # Initialize metrics
    precision = np.zeros(num_classes)
    recall = np.zeros(num_classes)
    f1_score = np.zeros(num_classes)
    support = np.zeros(num_classes)

    # Calculate metrics for each class
    for i in range(num_classes):
        TP = confusion_matrix[i, i]
        FP = np.sum(confusion_matrix[:, i]) - TP
        FN = np.sum(confusion_matrix[i, :]) - TP
        TN = np.sum(confusion_matrix) - (TP + FP + FN)

        # Precision, Recall, F1 Score
        precision[i] = TP / (TP + FP) if (TP + FP) > 0 else 0
        recall[i] = TP / (TP + FN) if (TP + FN) > 0 else 0
        f1_score[i] = 2 * (precision[i] * recall[i]) / (precision[i] + recall[i]) if (precision[i] + recall[i]) > 0 else 0

        # Support (number of true instances for each class)
        support[i] = TP + FN

    # Calculate weighted averages
    weighted_precision = np.sum(precision * support) / np.sum(support) if np.sum(support) > 0 else 0
    weighted_recall = np.sum(recall * support) / np.sum(support) if np.sum(support) > 0 else 0
    weighted_f1 = np.sum(f1_score * support) / np.sum(support) if np.sum(support) > 0 else 0

    return {
        'confusion_matrix': confusion_matrix,
        'weighted_precision': weighted_precision,
        'weighted_recall': weighted_recall,
        'weighted_f1': weighted_f1
    }

In [47]:
# Example usage
pred_labels = [0, 1, 2, 0, 1, 2, 1, 0, 2, 1]  # Predicted labels
true_labels = [0, 1, 1, 0, 0, 2, 1, 1, 2, 2]  # True labels

#pred_labels = np.random.randint(0, 16, size=100)  # Random predictions
#true_labels = np.random.randint(0, 16, size=100)  # Random true labels

results = statistics(pred_labels, true_labels)
print("Confusion Matrix:\n", results['confusion_matrix'])
print("Weighted Precision:", results['weighted_precision'])
print("Weighted Recall:", results['weighted_recall'])
print("Weighted F1 Score:", results['weighted_f1'])

Confusion Matrix:
 [[2 1 0]
 [1 2 1]
 [0 1 2]]
Weighted Precision: 0.6
Weighted Recall: 0.6
Weighted F1 Score: 0.6
